teamName: kubrix
appName: johnny-app-pr-test
repoUrl: https://github.com/kubriX-demo/kubrix-johnny-app-pr-test
createAppNamespace: true
stages:
  - name: "test"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        direct: true
  - name: "qa"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - test
  - name: "prod"
    openPr: true
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - qa
